[package]
name = "rust_kernel"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"
opt-level = 2

[profile.release]
panic = "abort"

[lib]
name = "kernel"
path = "src/kernel/main.rs"
crate-type = ["staticlib"]
