[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target="src/arch/x86/x86.json"

[target.x86]
runner = "src/kernel/runner.sh"

[alias]
ltest = "test --lib test"
