name: OS Compilation Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  # Tell Rust where to find our target specification
  RUST_TARGET_PATH: src/arch/x86

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Install required system dependencies for cross-compilation and assembly
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm gcc-multilib
    
    # Install Rust using rust-toolchain.toml from the repository
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable  # This will be overridden by rust-toolchain.toml
        override: true
        components: rust-src
    
    # Build the OS using make
    - name: Build OS
      env:
        # Ensure the target path is set for this step specifically as well
        RUST_TARGET_PATH: ${{ github.workspace }}/src/arch/x86
      run: make
